### PR TITLE
Add Solarized Dark preset

### PR DESCRIPTION
**Pull request by salarua**
# New Preset: Solarized Dark

As this is a variant of an existing preset, I'm leaving it on draft status until there's a system in place for distinguishing different versions apart.

## Description

Precision colors for machines and people.

## Palette
  
[Solarized](https://ethanschoonover.com/solarized/)

## Wallpaper

triangle-1663295680479-3225

# Checklist 

Before submitting the PR, I checked:

- [x] I've only modified one preset
- [ ] I've added the URL to my raw preset in `presets.json`
- [x] I've checked the format of each json files I modified
- [ ] (optional) I've added screenshots
- [x] The preset name is following preset naming guidelines.

## Publication 

- [x] I want to add my preset in the preset list.

Thanks for your submission we will review and merge it as quick as possible.

### CODE REVIEW

**Comment by salarua** [comment]
Since the current Solarized Dark preset is official, this can be added to Curated with no conflict.

**Comment by daudix-UFO** [comment]
I think yes 👍

**Comment by sharath1432** [comment]
hi

**Comment by 0xMRTT** [comment]
Hi

**Comment by sharath1432** [comment]
https://7r6.com/teesmaarkhantrailer

**Comment by sharath1432** [comment]
https://7r6.com/teesmaarkhantrailer

**Comment by 0xMRTT** [comment]
@daudix-UFO spammer detected

**Comment by daudix-UFO** [comment]
Ban Power Activated

**Comment by 0xMRTT** [comment]
> Are you okay if I finally merge this?

Yes

**Comment by daudix-UFO** [comment]
Alright, mega-merge in 3… 2… 1…

**Comment by 0xMRTT** [comment]
@salarua thanks :+1:

**Pull request merged**
