### PR TITLE
Add Rosé Pine themes

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
Adds Rose Pine themes

image

### CODE REVIEW

**Comment by 0xMRTT** [comment]
Thanks 👍👍

Is it ready ?

**Comment by ThatOneCalculator** [comment]
Sorry about that. I want to make a couple changes to the title buttons, I'll lyk when it's ready

**Comment by 0xMRTT** [comment]
Okay 👌

**Comment by vanillajonathan** [comment]
Rose Pine theme website: https://rosepinetheme.com/

**Comment by ThatOneCalculator** [comment]
Done

**Comment by 0xMRTT** [comment]
Thanks 👍👍👍👍

**Comment by 0xMRTT** [comment]
image

**Comment by 0xMRTT** [comment]
It's hard to see on Accent Color @ThatOneCalculator

**Comment by 0xMRTT** [comment]
image

**Comment by ThatOneCalculator** [comment]
Ah, I'll fix it in the morning

**Pull request merged**
