### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by daudix-UFO**
Refactor repo and polish official presets

### CODE REVIEW

**Comment by 0xMRTT** [comment]
So, by doing that we need to create a new repo in Gradience

**Comment by daudix-UFO** [comment]
Or rename this one to Presets

**Review by 0xMRTT — APPROVED** [review]
Just need to miae appropriated changes in Gradience itself and we can merge after

**Comment by daudix-UFO** [comment]
👍🚀

**Review by 0xMRTT — CHANGES_REQUESTED** [review]
OH, you missed to change urls in `official.json` and `curated.json`.

Change `presets` with `official` or `curated`

**Comment by daudix-UFO** [comment]
> OH, you missed to change urls in `official.json` and `curated.json`.
> 
> Change `presets` with `official` or `curated`

Yes, my bad, will fix soon ;)

_I reinstalled the system, so I need to install some apps to fix this_

PXL_20220909_140226490

**Review by 0xMRTT — APPROVED** [review]

**Comment by 0xMRTT** [comment]
I fixed :D

**Comment by daudix-UFO** [comment]
Thank you 🚀

**Comment by 0xMRTT** [comment]
I'm happy to say that the refactor will be available today :+1:

**Pull request merged**
