### PR TITLE
Add High Contrast theme

### LINKED ISSUE #65: feat: A high-contrast dark theme
### Feature description

Dark theme is common these days, but one problem of dark themes is that they often lack contrast. That is, they use light grey text on dark grey background. Or, when they use pure-black background, they lack borders, so UI elements are not discernable. For some users, this lack of contrast is not just a matter of aesthetics, but of accessibility.

Some applications, like JetBrain's IDE or VS Code, have high-contrast dark theme like below. The background is black and the text is white, so they are easy to read, and the UI elements have white borderlines, so they don't look all mingled together.

It seems there is no high-contrast dark theme in the presets, and I failed to make such a theme myself. How about adding a high-contrast dark theme in the presets?

### Additional Context
JetBrains' IDE

image

VS Code

image

MS Windows 10

image

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

### PR DESCRIPTION
**Pull request by tfuxu**
# New Preset: High Contrast

This isn't my work, files in this PR originate from issue #65 (more precisely from https://github.com/GradienceTeam/Community/issues/65#issuecomment-1326843903). I'm just putting them here, so that they can be further improved.

## Description

(Preset description should be in the preset file itself BTW) A simple high-contrast theme variation of GNOME high-contrast theme. It's more contrasted from original, and utilize more borders for easier visibility.

## Palette
  
OC, made by @daudix-UFO, from an idea by HubKing
  
### High Contrast:
Screenshot from 2022-11-28 17-22-03

### High Contrast Dark:
Screenshot from 2022-11-28 17-22-16

## Wallpaper

There's none

# Checklist

Before submitting the PR, I checked:

- [ ] ~I've only modified one preset~ (why can't I add more in one PR?)
- [x] I've added the URL to my raw preset in `presets.json`
- [x] I've checked the format of each json files I modified
- [x] (optional) I've added screenshots
- [x] The preset name is following preset naming guidelines.

## Publication

- [x] I want to add my preset in the preset list. (obviously)

Thanks for your submission we will review and merge it as quick as possible.

### CODE REVIEW

**Comment by daudix-UFO** [comment]
It needs window outlines BTW, but this needs some CSS

**Comment by asutoshvariar** [comment]
Is there any way to have a high-contrast scroll bar or would that be too much for this?

**Comment by daudix-UFO** [comment]
@asutoshvariar currently it have white outline, which is more visible than the defaults, but I can make it gray in addition

**Comment by daudix-UFO** [comment]
Can we merge this @tfuxu ?

**Comment by tfuxu** [comment]
I would like to add borders to more widgets as now, some of them, because of sharing the same color with a window background, don't have any distinctive indicators that a specific area is a background and the other is a widget.

Example with TextView:
Screenshot from 2023-01-11 00-13-11

**Comment by halfmexican** [comment]
I can help with the CSS. I recently added more borders to the pop theme to increase contrast

**Comment by daudix-UFO** [comment]
@halfmexican it would be very nice!

**Pull request closed without merging**
