### PR TITLE
Add Black Oled

### PR DESCRIPTION
**Pull request by EliasOfWaffle**
# New Preset: <Black Oled>

## Description
A Good Theme for Oled and Amoled displays

## Palette
A generated pallete using Adobe Colors, thanks to adobe colors

- [x] Adobe Colors Generated using Monocromatic mode
  
## Wallpaper

# Checklist 

Before submitting the PR, I checked:

- [x] I've only modified one preset
- [ ] I've added the URL to my raw preset in `presets.json`
- [x] I've checked the format of each json files I modified
- [ ] (optional) I've added screenshots
- [x] The preset name is following preset naming guidelines.

## Publication 

- [x] I want to add my preset in the preset list.

Thanks for your submission we will review and merge it as quick as possible.

### CODE REVIEW

**Comment by daudix-UFO** [comment]
Thank you for your contribution! I will review this preset asap

**Comment by daudix-UFO** [comment]
`oledsystem` is not very nice name, maybe we can get a better one?

**Comment by EliasOfWaffle** [comment]
> @EliasOfWaffle `oledsystem` is not very nice name, maybe we can get a better one?
> 
> _If you are OK with this we can replace `adwaita-black` with this preset, as this one is much better_

Sorry my english is very bad.
yes i will be very grateful with this replacement, thanks for consideration

**Comment by daudix-UFO** [comment]
Thank you for an amazing preset!

**Review by daudix-UFO — APPROVED** [review]

**Pull request merged**
