### PR TITLE
Create "Canta Dark" preset

### PR DESCRIPTION
**Pull request by qwertychouskie**
Based on https://github.com/vinceliuice/Canta-theme

# New Preset: Canta Dark

## Description
Based on https://github.com/vinceliuice/Canta-theme

## Palette
Not sure what this is

  
## Screenshots (optional)
https://i.imgur.com/WTVd1mb.png

## Wallpaper
Probably https://github.com/vinceliuice/Canta-theme/blob/master/wallpaper/Canta_wallpaper_01.jpeg or https://github.com/vinceliuice/Canta-theme/blob/master/wallpaper/canta-dark.png or https://github.com/vinceliuice/Canta-theme/blob/master/wallpaper/canta-wallpaper.png but there are a few other wallpapers in this folder too.

# Checklist 

Before submitting the PR, I checked:

- [X] I've only modified one preset
- [X] I've checked the format of each json files I modified
- [X] (optional) I've added screenshots
- [X] The preset name is following preset naming guidelines.

## Publication 

- [X] I want to add my preset in the preset list.

Thanks for your submission we will review and merge it as quick as possible.

### CODE REVIEW

**Comment by daudix** [comment]
Looks good, the only change I would do is use dark color for `@accent_fg_color` as currently contrast is very low. And change `@accent_color` from blue to green as it should be similar colors to `@accent_bg_color`

**Comment by qwertychouskie** [comment]
How about #00ce99 for `@accent_bg_color`?  Making the text black doesn't look very good IMHO.

`#feac00` is more accurate to the original theme, but since the conversion wasn't perfectly 1:1 anyways due to the differences between GTK3 and 4, I went with the green, which matched other aspects in the original theme better IMHO.  (See screenshots: https://github.com/vinceliuice/Canta-theme#screenshots)

**Comment by daudix** [comment]
If it has better contrast (or at least visible for example in checkbox) the go ahead :)

**Comment by qwertychouskie** [comment]
Checkboxes look better after the change to a slightly darker green.  If it's possible to use a black check but keep white text, that would be the best (that's how the original theme does it) but if that's not possible IMHO the colors are fine how they are now.

**Comment by daudix** [comment]
Hm, it seems like `@accent_color` haven't changed, after the fix I will merge

**Comment by daudix** [comment]
Oops, `@view_bg_color` also needs to be changed

**Comment by qwertychouskie** [comment]
@daudix-UFO Everything should be fixed and ready for merge now AFAIK.

**Comment by daudix** [comment]
LGTM, thanks for fixing all the issues!

**Comment by qwertychouskie** [comment]
Awesome!  I've always found the colors of Canta nicer/easier on my eyes than stock Adwaita Dark, so I'm happy to make it easily accessible for everyone :)

**Pull request merged**
