### PR TITLE
WIP: Adding Gruvbox Dark (waiting for a rename)

### PR DESCRIPTION
**Pull request by LyesSaadi**
kill me, i'm so dumb

We need to figure out a naming system before merging this (thus, the draft state).

EDIT: Context for others. This was an attempt at Gruvbox before @daudix-UFO's attempt. Wanted to submit it, but mistakenly opened the PR in my own fork :upside_down_face:...

### CODE REVIEW

**Comment by daudix-UFO** [comment]
What about `preset-name-(author_name).json` ?

In future it will be cool to display author in app UI

**Comment by 0xMRTT** [comment]
> What about `preset_name-(author_name).json` ?
> 
> In future it will be cool to display author in app UI

It already support author name 😅

**Comment by 0xMRTT** [comment]
@daudix-UFO and what about this one ?

**Comment by daudix-UFO** [comment]
We need to do something with this 😅

**Comment by daudix-UFO** [comment]
Alright, just in case there is `git revert <commit>`

**Comment by 0xMRTT** [comment]
@LyesSaadi maybe rename it in something else ? @daudix-UFO

**Comment by daudix-UFO** [comment]
Oh F(UTC TIME)

**Comment by 0xMRTT** [comment]
NOOOOOO, it's just got merged in a wrong dir!!

We also need to add other presets to the `presets.json` file

**Comment by LyesSaadi** [comment]
LOL xD

**Comment by LyesSaadi** [comment]
Later :sweat_smile: (prolly tomorrow) ! Lots of work tonight...

**Comment by 0xMRTT** [comment]
Good luck :rocket:

**Pull request merged**
