### PR TITLE
Port Yaru Bark (Light + Dark)

### PR DESCRIPTION
**Pull request by asutoshvariar**
# New Preset: Yaru Bark

The Yaru Bark theme, for use with Gradience.

## Description
The Yaru Bark theme, for use with Gradience.

## Palette
  

- [x] None
  
## Wallpaper

# Checklist 

Before submitting the PR, I checked:

- [ ] I've only modified one preset
- [ ] I've added the URL to my raw preset in `presets.json`
- [x] I've checked the format of each json files I modified
- [ ] (optional) I've added screenshots
- [x] The preset name is following preset naming guidelines.

## Publication 

- [x] I want to add my preset in the preset list.

Thanks for your submission we will review and merge it as quick as possible.

### CODE REVIEW

**Comment by daudix** [comment]
Looks nice, but I don't really like the black @card_shade_color, is it like this in ubuntu yaru?

**Comment by asutoshvariar** [comment]
It's not mentioned in the adw-colors css file. However, default Adwaita does seem to have an alpha value of 0.07. Should that be changed?

**Comment by daudix** [comment]
I think so

**Comment by asutoshvariar** [comment]
Actually, looking back through the files (and the default themes), Adwaita Dark has an alpha value of 0.36 and Adwaita (Light) has an alpha value of 0.07, both of which are accurately reflected in the stylesheets. Has there been any change to Ubuntu that adw-colors hasn't reflected?

Sorry about the confusion.

**Comment by daudix** [comment]
I don't know, usually I leave Adwaita colors if theme doesn't specify them

**Comment by asutoshvariar** [comment]
I guess this could be a matter of preference or the rounded corners? Might be safe to get a second opinion on this (couldn't find anything related to card_shade_color in the yaru repo).

**Comment by daudix** [comment]
If there are no mentions of it that likely means they fallback to Adwaita

**Comment by daudix** [comment]
Alright, I will make tweaks later, merging!

**Pull request merged**
