### PR TITLE
Add Kanagawa theme

### PR DESCRIPTION
**Pull request by ScribeAwoken**
# New Preset: Kanagawa

Since it's a popular terminal theme that felt oddly missing from the available presets, I decided to make a Kanagawa theme.

Also worth noting: I was not able to add the raw url to presets.json, since that file doesn't seem to exist in the repo.

## Description

A dark theme based on rebelot's Kanagawa neovim color scheme.

## Palette
  

@rebelot's [Kanagawa](https://github.com/rebelot/kanagawa.nvim) color scheme for Neovim.
  
## Screenshots (optional)

image

## Wallpaper

I feel like the Hokusai print that gave the theme its name would be the most fitting choice of background here.

Under-The-Wave-Off-Kanagawa

# Checklist 

Before submitting the PR, I checked:

- [x] I've only modified one preset
- [ ] I've added the URL to my raw preset in `presets.json`
- [x] I've checked the format of each json files I modified
- [x] (optional) I've added screenshots
- [x] The preset name is following preset naming guidelines.

## Publication 

- [x] I want to add my preset in the preset list.

Thanks for your submission we will review and merge it as quick as possible.

### CODE REVIEW

**Comment by daudix-UFO** [comment]
Give me a minute ;)

**Comment by daudix-UFO** [comment]
@ScribeAwoken Overall looks fantastic, good job!

But, I have a few nitpicks:

Text have low contrast in dialogs

изображение

Popups have this issue too

изображение

**Comment by ScribeAwoken** [comment]
Alright. I'm gonna be busy for the next couple of hours, but I should be able to put together some tweaks by tomorrow morning. just distro-hopped and I'm in the middle of troubleshooting a known issue with discord on the distro I switched to

**Comment by daudix-UFO** [comment]
No need to hurry, feel free to finish this when you will have time ;)

**Comment by ScribeAwoken** [comment]
lmao so the one issue I had with my computer took up way less of my lunch break than I expected, so here's a preview of the change I made to the popovers and dialogs. Instead of using the lightest "black" shade the Kanagawa color scheme uses for the background, I used the darkest one (which I wasn't using before). this should have better contrast with the text color.

image

image

**Comment by daudix-UFO** [comment]
Looks fantastic! Thank you 🔥

**Pull request merged**
