### PR TITLE
feat: add the everblush preset

### PR DESCRIPTION
**Pull request by Ultra980**
# New Preset: Everblush

## Description

A preset with the [Everblush](https://github.com/Everblush) colour scheme

## Palette
  

[Everblush](https://github.com/Everblush)
  
## Wallpaper

# Checklist 

Before submitting the PR, I checked:

- [X] I've only modified one preset
- [X] I've checked the format of each json files I modified
- [ ] (optional) I've added screenshots
- [X] The preset name is following preset naming guidelines.

## Publication 

- [X] I want to add my preset in the preset list.

Thanks for your submission we will review and merge it as quick as possible.

### CODE REVIEW

**Comment by daudix** [comment]
Overall looks awesome, good job!

There are one important issue tho, the accent color has awful contrast

Снимок экрана от 2023-07-12 23-22-11
Снимок экрана от 2023-07-12 23-22-14
Снимок экрана от 2023-07-12 23-22-39
Снимок экрана от 2023-07-12 23-22-43
Снимок экрана от 2023-07-12 23-22-53

**Comment by daudix** [comment]
I would use more classic blue (exists in palette) as accent so it is visible

**Comment by Ultra980** [comment]
Right, I'll do that.

**Comment by Ultra980** [comment]
done.

**Comment by 0xMRTT** [comment]
Could you use Gradience Nightly and add sidebar color ?

**Comment by daudix** [comment]
Don't forget to fix `@accent_bg_color` as well ;)

**Comment by Ultra980** [comment]
> Don't forget to fix `@accent_bg_color` as well ;)

Done!

**Comment by Ultra980** [comment]
> Could you use Gradience Nightly and add sidebar color ?

Is there a way to use Nightly with nix?

**Comment by daudix** [comment]
About nightly, if you want you can update preset when new version will come out ;)

**Comment by daudix** [comment]
What's up with switches tho

image

**Comment by Ultra980** [comment]
> What's up with switches tho
> 
> image

I noticed that as well, what colour do they use?

**Comment by daudix** [comment]
`@accent_bg_color`, just make it blue

**Comment by Ultra980** [comment]
I made it a lighter gray

**Comment by daudix** [comment]
both accent colors should have same color, so decide gray or blue

**Comment by daudix** [comment]
alright, links are visible and switch states are pretty distinguishable, merging!

**Pull request merged**
