### PR TITLE
Rename to `next`

### PR DESCRIPTION
**Pull request by daudix-UFO**
As all presets are moved to `v2`, and there is no need to have a copy of them in `main`, as we can just leave a link to the `v2`

about rename to `next`, why not?

_There is PR for Gradience too: https://github.com/GradienceTeam/Gradience/pull/390_

### CODE REVIEW

**Comment by 0xMRTT** [comment]
I maybe I didn't understand but why did you removed all presets ? 

I understand that this branch will be used for compatibility? But if this branch is used for compatibility we can't rename main

**Comment by daudix-UFO** [comment]
Solution is interesting, the purpose of `presets.json` is to put links to raw `theme.json`, as we can put link to whatever site, why not put a link to v2

**Comment by daudix-UFO** [comment]
In short, we put links in `presets.json` > `main` from `official.json` and `curated.json` > `next` combined

**Comment by 0xMRTT** [comment]
Oh, yes 😅

So, we add presets.json in main with a link to presets in the current branch

**Comment by daudix-UFO** [comment]
This should work in new version and older ones

**Comment by daudix-UFO** [comment]
> Oh, yes sweat_smile
> 
> So, we add presets.json in main with a link to presets in the current branch

Exactly

**Comment by 0xMRTT** [comment]
And in which branch preset will be stored ?

**Comment by daudix-UFO** [comment]
In `next`, and `next` is renamed `v2`

**Comment by 0xMRTT** [comment]
But why did you removed every presets ?

**Comment by daudix-UFO** [comment]
I'm so stupid, this is changes for `main` 🤦

**Comment by daudix-UFO** [comment]
Now it's correct

**Review by 0xMRTT — APPROVED** [review]
Now I understand 🤣

**Pull request merged**
