### PR TITLE
Add Breeze Light and Breeze Dark

### PR DESCRIPTION
**Pull request by dominichayesferen**
# New Preset: Breeze Light and Breeze Dark

## Description

The default light and dark Breeze colour schemes, directly ported to Gradience unofficially. The original KDE colour schemes are by the KDE Visual Design Group.

## Palette
  

- [x] None
  
## Screenshots (optional)

image
image

## Wallpaper

https://invent.kde.org/plasma/breeze/-/tree/master/wallpapers/Next/contents

# Checklist 

Before submitting the PR, I checked:

- [ ] I've only modified one preset
- [ ] I've added the URL to my raw preset in `presets.json`
- [x] I've checked the format of each json files I modified
- [x] (optional) I've added screenshots
- [x] The preset name is following preset naming guidelines.

## Publication 

- [x] I want to add my preset in the preset list.

Thanks for your submission we will review and merge it as quick as possible.

### CODE REVIEW

**Comment by daudix-UFO** [comment]
Awesome! the only complain is white shadows in dark variant

**Comment by dominichayesferen** [comment]
> Awesome! the only complain is white shadows in dark variant

Could you indicate where the shadows are white? If you mean the borders and window borders being white, this is intentional as Breeze's QStyle's borders are based on the text colour, meaning they become a transparent white in Breeze Dark (additionally, Breeze KWin's borders also use the foreground colour last I checked).

**Comment by daudix-UFO** [comment]
`@shade_color`

image

**Comment by dominichayesferen** [comment]
ah. I'mma fix that real quick, then.

**Review by daudix-UFO — APPROVED** [review]

**Comment by daudix-UFO** [comment]
Thanks!

**Pull request merged**
